server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: cjh1020
mybatis:
  mapper-locations: classpath:mapper/*.xml
